# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  backend "s3" {
    bucket         = "norlys-organizational-units-ccoe-tfstate"
    key            = "ccoe/terraform.tfstate"
    encrypt        = true
    region         = "eu-north-1"
    dynamodb_table = "norlys-organizational-units-ccoe-tfstate-lock"
    profile        = "ccoe"
  }
}
