# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  backend "s3" {
    bucket         = "norlys-organizational-units-operations-tfstate"
    key            = "operations/terraform.tfstate"
    encrypt        = true
    region         = "eu-north-1"
    dynamodb_table = "norlys-organizational-units-operations-tfstate-lock"
    profile        = "operations"
  }
}
